export const GET_ALL_QUESTIONS = 'GET_ALL_QUESTIONS';
export const ANSWER_QUESTION = 'ANSWER_QUESTION';
export const ADD_QUESTION = 'ADD_QUESTION';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const UPDATE_USER_QUESTIONS = 'UPDATE_USER_QUESTIONS';
export const LOGOUT = 'LOGOUT';